### ISSUE TITLE
On Linux, "Ctrl-\" is a better alternative for toggling tree view.

### ISSUE THREAD

**Issue by lancelafontaine** [nwinkler/atom-keyboard-shortcuts#3]
Not sure if this shortcut is used on other operating systems.

**Comment by nwinkler** [comment]
Feel free to provide a pull request with the additional shortcut. I don't use Linux, I can't verify.

The problem with `\` is that it's difficult to do depending on the keyboard layout/locale. Feel free to add it as an alternative.
